This notebook sets up a new Terra data table (`watershed_sv_run`) where we store the inputs and outputs of the Watershed-SV workflow.

This notebook should take about 1 minute to run.

## Setup

In [1]:
BiocManager::install('AnVILGCP')

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org

Bioconductor version 3.21 (BiocManager 1.30.25), R 4.5.0 (2025-04-11)

Warning message:
“package(s) not installed when version(s) same as or greater than current; use
  `force = TRUE` to re-install: 'AnVILGCP'”
Old packages: 'alabaster.base', 'AnnotationHub', 'AnVIL', 'base64enc', 'BH',
  'bigrquery', 'BiocFileCache', 'BiocGenerics', 'BiocManager', 'BiocParallel',
  'blob', 'boot', 'broom', 'bslib', 'cli', 'clock', 'cluster', 'colorspace',
  'commonmark', 'cowplot', 'cpp11', 'credentials', 'crosstalk', 'curl',
  'data.table', 'dbplyr', 'DelayedArray', 'DESeq2', 'devtools', 'diffobj',
  'digest', 'downlit', 'dplyr', 'DT', 'dtplyr', 'edgeR', 'evaluate',
  'ExperimentHub', 'fansi', 'fitdistrplus', 'forcats', 'foreign',
  'futile.logger', 'future', 'future.apply', 'gargle', 'generics',
  'GenomeInfoDb', 'gert', 'ggplot2', 'ggridges', 'gh', 'globals',
  'googleAuthR', 'googledrive', 'googlesheets4', 'gplots', 'h5mread', 'haven',
  'here', 'hms', 'htmltools', 'httr', 'httr2', 'igraph', 'irlba', 'isoband',
  'KEGGREST', 'knitr', 'later', 'lattice', 'latticeExtra', 'leidenbase',
  'lifecycle', 'limma', 'listenv', 'lubridate', 'magrittr', 'Matrix', 'mgcv',
  'openssl', 'parallelly', 'patchwork', 'pbapply', 'pillar', 'pkgbuild',
  'pkgdown', 'pkgload', 'plotly', 'progressr', 'promises', 'purrr', 'ragg',
  'rapidjsonr', 'rappdirs', 'Rcpp', 'RcppAnnoy', 'RcppArmadillo', 'readr',
  'reshape2', 'restfulr', 'reticulate', 'rhdf5', 'rlang', 'rmarkdown', 'ROCR',
  'roxygen2', 'rprojroot', 'Rsamtools', 'RSQLite', 'rstudioapi', 'rversions',
  'rvest', 'S4Arrays', 'scales', 'sctransform', 'selectr', 'Seurat',
  'SeuratObject', 'shiny', 'SingleCellExperiment', 'sp', 'spam', 'SparseArray',
  'spatstat.data', 'spatstat.explore', 'spatstat.geom', 'spatstat.random',
  'spatstat.univar', 'spatstat.utils', 'statmod', 'stringr',
  'SummarizedExperiment', 'survival', 'systemfonts', 'tensor', 'testthat',
  'textshaping', 'tibble', 'tidyr', 'timechange', 'tinytex', 'usethis', 'utf8',
  'uuid', 'uwot', 'V8', 'vctrs', 'viridisLite', 'vroom', 'waldo', 'xfun',
  'XML', 'xml2', 'xtable', 'yaml', 'zip', 'zoo'

In [2]:
library(AnVILGCP)
library(data.table)

Similar to notebook 1, the `avtable()` function is used to import Terra data tables into R as a data frame.

In [ ]:
anvil_file_tbl <- setDT(avtable('anvil_file'   ))
anno_meta_tbl  <- setDT(avtable('anno_metadata'))

## Construct Terra data table specifying workflow inputs

Here we pull file references from the `anvil_file` and `anno_metadata` tables and organize them into a new, single-row Terra data table. Each column of this new table represents an input to the Watershed-SV annotation workflow.

In [4]:
watershed_sv_run_tbl <-
  cbind(
    anvil_file_tbl[, .(fnm=`pfb:file_name`, `pfb:drs_uri`) |> transpose(make.names='fnm')],
    anno_meta_tbl [, .(fnm=basename(file),       file    ) |> transpose(make.names='fnm')]
  )[, .(# Renaming and keeping only the needed files.
        # The name of the first column determines the name of the Terra table.
        watershed_sv_run = 'MAGE_1000G',
    
        # Annotation data
        ABC_enhancers        = ABC_enhancers.merged.All.sorted.11col.region.hg38.bed,
        bw_CADD              = `CADD_GRCh38-v1.6.bw`,
        bw_GC                = gc5Base.bw,
        bw_linsight          = LINSIGHT_hg38.bw,
        bw_phastcon          = hg38.phastCons20way.bw,
        cpg_file             = cpgIslandExt.txt,
        enhancers            = matrix_hs.csv,
        gencode_genes        = gencode.v26.GRCh38.genes.gtf,
        genome_bound_file    = gtex_human_reference.genome,
        primary_cells        = hs_primary.txt,
        remap_crm            = remap2020_crm_macs2_hg38_v1_0.bed.gz,
        roadmap_tar          = roadmap_all_gtex.tar.gz,
        TADs_tar             = TAD.tar.gz,
        vep_cache_tar        = vep_cache.tar.gz,
        
        # Genetic/phenotypic data
        metadata        = sample.metadata.MAGE.v1.0.txt,
        expression_file = paste0(avstorage(),'/data/derived/mage_expression-watershed_sv_input.tsv'),
        gene_list       = paste0(avstorage(),'/data/derived/mage_gene_list.csv'),
        input_vcf       = paste0(avstorage(),'/data/derived/ALL.wgs.mergedSV.v8.20130502.svs.genotypes-edited.vcf.gz'),
        maf_file        = paste0(avstorage(),'/data/derived/1kGp3_sv_maf_file.tsv'),
    
        # Watershed-SV options
        CN_mode = 'extract',
        collapse_instruction = collapse_annotation_instructions.tsv,
        collapse_mode = 'gene-sv',
        expression_field = 'MedZ',
        exprssion_id_field = 'Ind',
        filter_ethnicity = 'false',
        filter_rare = 'false',
        filters = '[".", "PASS"]',
        flank = 1e4,
        length_field = 'SVLEN',
        length_mode = 'extract',
        maf_field = 'Max_MAF',
        maf_mode = 'upload',
        min_support_tissue = 1,
        pipeline = 'population',
        remove_control_genes = 'true',
        zscore_threshold = 3
      )
]
watershed_sv_run_tbl

  watershed_sv_run
1 MAGE_1000G
  ABC_enhancers
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/ABC_enhancers.merged.All.sorted.11col.region.hg38.bed
  bw_CADD
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/CADD_GRCh38-v1.6.bw
  bw_GC
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/gc5Base.bw
  bw_linsight
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/LINSIGHT_hg38.bw
  bw_phastcon
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/hg38.phastCons20way.bw
  cpg_file
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/cpgIslandExt.txt
  enhancers
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/matrix_hs.csv
  gencode_genes
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/gencode.v26.GRCh38.genes.gtf
  genome_bound_file
1 gs://fc-secure-ca459dc2-db2a-4dbb-8747-baea7e6c6669/data/raw/annotation/gtex_human_reference.genome
  ⋯ filters       flank length_field length_mode maf_field maf_mode
1 ⋯ [".", "PASS"] 10000 SVLEN        extract     Max_MAF   upload
  min_support_tissue pipeline   remove_control_genes zscore_threshold
1 1                  population true                 3

## Upload
`AnVILGCP::avtable_import()` is used to upload an R dataframe as a Terra data table.

In [5]:
avtable_import(watershed_sv_run_tbl, 'watershed_sv_run')

pageSize = 1 rows (1 pages)

  page from_row to_row job_id                               status   message
1 1    1        1      95d5122e-f8c4-4a9e-a4fb-5deb72366472 Uploaded NA