This notebook runs the Watershed algorithm on the annotation file created by the Watershed-SV annotation pipeline.

This notebook should take about 3 minutes to run.


## Setup

In [1]:
library(AnVILGCP)
library(data.table)

# Watershed requirements
install.packages(c('PRROC','optparse','lbfgs'))

# Watershed algorithm code
anno_meta_tbl <- setDT(avtable('anno_metadata'))
watershed_folder <- anno_meta_tbl[file %in% grep('Watershed_with_tweaks/', file, val=T), file]
system(paste('gcloud storage cp -r', watershed_folder, '.'))

Installing packages into ‘/home/jupyter/packages’
(as ‘lib’ is unspecified)

also installing the dependency ‘getopt’


Registered S3 methods overwritten by 'AnVIL':
  method                         from
  print.avworkflow_configuration AnVILGCP
  print.gcloud_sdk_result        AnVILGCP

In [2]:
subset_watershed_sv_output <- fread('subset_training_data.tsv')
  full_watershed_sv_output <- fread(  'full_training_data.tsv')
gene_sample_z       <- fread('mage_expression-watershed_sv_input.tsv')

# Define N2 Pairs
[See here](https://github.com/BennyStrobes/Watershed?tab=readme-ov-file#input-file) the format Watershed expects as input.

In [3]:
tmp <- subset_watershed_sv_output[, N2pair := as.integer(N2pair)
  ][, N2pair := fifelse(.N==2,.GRP,NA), by=GeneName
  ][, setcolorder(.SD, setdiff(names(.SD), 'N2pair'))
  ][, gene := NULL
]
tmp2 <- full_watershed_sv_output[, N2pair := as.integer(N2pair)
  ][, N2pair := fifelse(.N==2,.GRP,NA), by=GeneName
  ][, setcolorder(.SD, setdiff(names(.SD), 'N2pair'))
]

In [4]:
head(tmp)

    SubjectID GeneName
1   HG00146   ENSG00000174807:UW_VH_3482
2   NA18553   ENSG00000168303:DUP_gs_CNV_7_40131223_40160568
3   HG03127   ENSG00000181192:DUP_gs_CNV_10_12111903_12124450
4   HG03127   ENSG00000181192:DUP_gs_CNV_10_12102547_12113247
5   HG03097   ENSG00000140470:DEL_pindel_43036
6   HG03118   ENSG00000162734:BI_GS_DEL1_B2_P0161_179
7   HG03084   ENSG00000138639:DEL_pindel_12414
8   NA18522   ENSG00000082068:DEL_pindel_15235
9   NA19719   ENSG00000184226:DUP_uwash_chr13_66891604_66901672
10  HG02090   ENSG00000111679:BI_GS_DEL1_B2_P1966_722
11  NA20876   ENSG00000184226:BI_GS_DEL1_B3_P2161_2
12  HG01055   ENSG00000133019:UW_VH_8124
13  HG02583   ENSG00000145781:UW_VH_14273
14  HG02731   ENSG00000171759:UW_VH_4103
15  HG03247   ENSG00000051620:DEL_pindel_20533
16  NA12828   ENSG00000146731:DUP_uwash_chr7_56031072_56186821
17  HG02494   ENSG00000159377:DUP_delly_DUP23941
18  NA19338   ENSG00000107959:BI_GS_DEL1_B3_P1691_7
19  NA18621   ENSG00000172456:DEL_pindel_738
20  HG00663   ENSG00000170745:DUP_gs_CNV_2_17937146_18216823
21  HG01853   ENSG00000174807:UW_VH_13686
22  HG03135   ENSG00000152078:UW_VH_22151
23  HG00141   ENSG00000169926:DUP_uwash_chr15_31110505_31330839
24  HG01363   ENSG00000116667:BI_GS_DEL1_B2_P0185_310
25  HG02481   ENSG00000130764:DUP_gs_CNV_1_3734485_3844788
26  HG02545   ENSG00000165752:UW_VH_8079
27  HG04177   ENSG00000184226:UW_VH_16198
28  HG01125   ENSG00000116667:DEL_pindel_1695
29  NA19385   ENSG00000198876:BI_GS_DEL1_B5_P1580_84
30  NA18504   ENSG00000051620:DEL_pindel_20533
⋮   ⋮         ⋮
229 HG02471   ENSG00000168282:DEL_pindel_40224
230 NA19393   ENSG00000172403:UW_VH_8741
231 HG03091   ENSG00000184226:DUP_uwash_chr13_66891604_66901672
232 NA19404   ENSG00000082068:BI_GS_DEL1_B5_P0923_417
233 HG02429   ENSG00000138639:DEL_pindel_12421
234 HG01809   ENSG00000082068:DEL_pindel_15237
235 HG01669   ENSG00000172456:DEL_pindel_734
236 HG02026   ENSG00000184226:UW_VH_6503
237 HG01812   ENSG00000071189:DEL_pindel_21870
238 HG02580   ENSG00000165752:UW_VH_8079
239 HG03064   ENSG00000181192:DUP_uwash_chr10_12092804_12171370
240 HG03311   ENSG00000162734:BI_GS_DEL1_B2_P0161_179
241 HG00463   ENSG00000182308:BI_GS_DEL1_B3_P0735_35
242 HG03696   ENSG00000178038:DUP_gs_CNV_3_46667900_46756660
243 HG02888   ENSG00000172403:UW_VH_8741
244 HG00533   ENSG00000107959:DUP_gs_CNV_10_3179999_3227801
245 NA18749   ENSG00000172456:DEL_pindel_738
246 NA19338   ENSG00000035115:BI_GS_DEL1_B4_P0251_46
247 HG01912   ENSG00000174807:UW_VH_3482
248 HG01853   ENSG00000166387:DUP_gs_CNV_11_7545083_7650780
249 HG01988   ENSG00000184226:DUP_uwash_chr13_66891604_66901672
250 HG01965   ENSG00000116667:BI_GS_DEL1_B2_P0185_348
251 HG03166   ENSG00000063438:DUP_delly_DUP66791
252 HG01606   ENSG00000100505:BI_GS_DEL1_B5_P2261_114
253 HG02494   ENSG00000171759:BI_GS_DEL1_B2_P2062_577
254 HG02624   ENSG00000184022:DUP_gs_CNV_1_248572358_248596103
255 HG01363   ENSG00000168280:BI_GS_DEL1_B1_P0400_8
256 NA12889   ENSG00000175868:DUP_gs_CNV_11_14873676_14919955
257 HG02981   ENSG00000051620:DEL_pindel_20533
258 HG02545   ENSG00000152078:UW_VH_22151
    SVTYPE_DUP_gene_body SVTYPE_DEL_gene_body SVTYPE_INV_gene_body
1   0                    0                    0
2   1                    0                    0
3   1                    0                    0
4   1                    0                    0
5   0                    1                    0
6   0                    1                    0
7   0                    1                    0
8   0                    0                    0
9   0                    1                    0
10  0                    1                    0
11  0                    1                    0
12  0                    1                    0
13  0                    1                    0
14  0                    1                    0
15  0                    0                    0
16  1                    0                    0
17  1                    0                    0
18  0                    1                    0
19  0                    1                    0
20  1                    0                    0
21  0                    0                    0
22  0                    1                    0
23  1                    0                    0
24  0                    1                    0
25  1                    0                    0
26  0                    1                    0
27  0                    1                    0
28  0                    1                    0
29  0                    1                    0
30  0                    0                    0
⋮   ⋮                    ⋮                    ⋮
229 0                    1                    0
230 0                    0                    0
231 0                    1                    0
232 0                    1                    0
233 0                    1                    0
234 0                    1                    0
235 0                    1                    0
236 0                    1                    0
237 0                    1                    0
238 0                    1                    0
239 1                    0                    0
240 0                    1                    0
241 0                    0                    0
242 1                    0                    0
243 0                    0                    0
244 0                    0                    0
245 0                    1                    0
246 0                    0                    0
247 0                    0                    0
248 1                    0                    0
249 0                    1                    0
250 0                    1                    0
251 1                    0                    0
252 0                    1                    0
253 0                    0                    0
254 1                    0                    0
255 0                    1                    0
256 1                    0                    0
257 0                    0                    0
258 0                    1                    0
    SVTYPE_DUP_tss_flank SVTYPE_DEL_tss_flank SVTYPE_DUP_tes_flank
1   0                    0                    0
2   1                    0                    0
3   0                    0                    1
4   0                    0                    0
5   0                    0                    0
6   0                    1                    0
7   0                    0                    0
8   0                    1                    0
9   0                    0                    0
10  0                    1                    0
11  0                    0                    0
12  0                    0                    0
13  0                    0                    0
14  0                    0                    0
15  0                    0                    0
16  1                    0                    1
17  1                    0                    1
18  0                    0                    0
19  0                    0                    0
20  0                    0                    0
21  0                    1                    0
22  0                    0                    0
23  1                    0                    0
24  0                    0                    0
25  1                    0                    1
26  0                    0                    0
27  0                    0                    0
28  0                    0                    0
29  0                    0                    0
30  0                    0                    0
⋮   ⋮                    ⋮                    ⋮
229 0                    0                    0
230 0                    1                    0
231 0                    0                    0
232 0                    0                    0
233 0                    0                    0
234 0                    0                    0
235 0                    0                    0
236 0                    0                    0
237 0                    0                    0
238 0                    0                    0
239 0                    0                    1
240 0                    1                    0
241 0                    1                    0
242 1                    0                    1
243 0                    1                    0
244 1                    0                    0
245 0                    0                    0
246 0                    0                    0
247 0                    0                    0
248 0                    0                    0
249 0                    0                    0
250 0                    0                    0
251 0                    0                    0
252 0                    0                    0
253 0                    0                    0
254 1                    0                    1
255 0                    0                    0
256 1                    0                    0
257 0                    0                    0
258 0                    0                    0
    SVTYPE_DEL_tes_flank af         ⋯ is_ABC_SV_tes_flank
1   1                    0.00299521 ⋯ 0
2   0                    0.00059904 ⋯ 0
3   0                    0.00638978 ⋯ 1
4   0                    0.00579073 ⋯ 0
5   0                    0.00658946 ⋯ 0
6   0                    0.00798722 ⋯ 0
7   0                    0.00718850 ⋯ 0
8   0                    0.00199681 ⋯ 0
9   0                    0.00499201 ⋯ 0
10  0                    0.00019968 ⋯ 0
11  0                    0.00239617 ⋯ 0
12  0                    0.00019968 ⋯ 0
13  0                    0.00678914 ⋯ 0
14  1                    0.00439297 ⋯ 0
15  1                    0.00539137 ⋯ 0
16  0                    0.00019968 ⋯ 1
17  0                    0.00279553 ⋯ 0
18  0                    0.00379393 ⋯ 0
19  0                    0.00119808 ⋯ 0
20  0                    0.00019968 ⋯ 0
21  0                    0.00119808 ⋯ 0
22  0                    0.00758786 ⋯ 0
23  0                    0.00019968 ⋯ 0
24  0                    0.00259585 ⋯ 0
25  0                    0.00039936 ⋯ 1
26  0                    0.00619010 ⋯ 0
27  0                    0.00239617 ⋯ 0
28  0                    0.00559105 ⋯ 0
29  0                    0.00019968 ⋯ 0
30  1                    0.00539137 ⋯ 0
⋮   ⋮                    ⋮          ⋱ ⋮
229 0                    0.00479233 ⋯ 0
230 0                    0.00579073 ⋯ 0
231 0                    0.00499201 ⋯ 0
232 0                    0.00479233 ⋯ 0
233 0                    0.00758786 ⋯ 0
234 0                    0.00439297 ⋯ 0
235 0                    0.00299521 ⋯ 0
236 0                    0.00079872 ⋯ 0
237 0                    0.00998403 ⋯ 0
238 0                    0.00619010 ⋯ 0
239 0                    0.00599042 ⋯ 1
240 0                    0.00798722 ⋯ 0
241 0                    0.00559105 ⋯ 0
242 0                    0.00019968 ⋯ 0
243 0                    0.00579073 ⋯ 0
244 0                    0.00019968 ⋯ 0
245 0                    0.00119808 ⋯ 0
246 1                    0.00039936 ⋯ 0
247 1                    0.00299521 ⋯ 0
248 0                    0.00039936 ⋯ 0
249 0                    0.00499201 ⋯ 0
250 0                    0.00019968 ⋯ 0
251 0                    0.00039936 ⋯ 0
252 0                    0.00439297 ⋯ 0
253 1                    0.00019968 ⋯ 0
254 0                    0.00239617 ⋯ 0
255 0                    0.00019968 ⋯ 0
256 0                    0.00019968 ⋯ 0
257 1                    0.00539137 ⋯ 0
258 0                    0.00758786 ⋯ 0
    mean_GC_content_tes_flank top10_LINSIGHT_tes_flank top10_phastCON_tes_flank
1   48.35777                  0.13788000               0.6911
2    0.00000                  0.00000000               0.0000
3   45.63265                  0.51951611               0.7593
4    0.00000                  0.00000000               0.0000
5    0.00000                  0.00000000               0.0000
6    0.00000                  0.00000000               0.0000
7    0.00000                  0.00000000               0.0000
8    0.00000                  0.00000000               0.0000
9    0.00000                  0.00000000               0.0000
10   0.00000                  0.00000000               0.0000
11   0.00000                  0.00000000               0.0000
12   0.00000                  0.00000000               0.0000
13   0.00000                  0.00000000               0.0000
14  36.07570                  0.05204305               0.9848
15  49.13043                  0.04801141               0.4367
16  47.56000                  0.95809681               1.0000
17  44.43626                  0.98880230               1.0000
18   0.00000                  0.00000000               0.0000
19   0.00000                  0.00000000               0.0000
20   0.00000                  0.00000000               0.0000
21   0.00000                  0.00000000               0.0000
22   0.00000                  0.00000000               0.0000
23   0.00000                  0.00000000               0.0000
24   0.00000                  0.00000000               0.0000
25  63.33000                  0.91935900               1.0000
26   0.00000                  0.00000000               0.0000
27   0.00000                  0.00000000               0.0000
28   0.00000                  0.00000000               0.0000
29   0.00000                  0.00000000               0.0000
30  49.13043                  0.04801141               0.4367
⋮   ⋮                         ⋮                        ⋮
229  0.00000                  0.00000000               0.0000
230  0.00000                  0.00000000               0.0000
231  0.00000                  0.00000000               0.0000
232  0.00000                  0.00000000               0.0000
233  0.00000                  0.00000000               0.0000
234  0.00000                  0.00000000               0.0000
235  0.00000                  0.00000000               0.0000
236  0.00000                  0.00000000               0.0000
237  0.00000                  0.00000000               0.0000
238  0.00000                  0.00000000               0.0000
239 47.54000                  0.94782850               0.9982
240  0.00000                  0.00000000               0.0000
241  0.00000                  0.00000000               0.0000
242 56.28882                  0.06922780               0.2142
243  0.00000                  0.00000000               0.0000
244  0.00000                  0.00000000               0.0000
245  0.00000                  0.00000000               0.0000
246 41.86271                  0.06503090               0.9118
247 48.35777                  0.13788000               0.6911
248  0.00000                  0.00000000               0.0000
249  0.00000                  0.00000000               0.0000
250  0.00000                  0.00000000               0.0000
251  0.00000                  0.00000000               0.0000
252  0.00000                  0.00000000               0.0000
253 38.37217                  0.08542180               0.0000
254 34.64400                  0.07034342               0.5594
255  0.00000                  0.00000000               0.0000
256  0.00000                  0.00000000               0.0000
257 49.13043                  0.04801141               0.4367
258  0.00000                  0.00000000               0.0000
    top10_CADD_tes_flank max_cpgpct_tes_flank remap_crm_score_tes_flank
1   13.5710               0.0                   64
2    0.0000               0.0                    0
3   15.7500               0.0                  418
4    0.0000               0.0                    0
5    0.0000               0.0                    0
6    0.0000               0.0                    0
7    0.0000               0.0                    0
8    0.0000               0.0                    0
9    0.0000               0.0                    0
10   0.0000               0.0                    0
11   0.0000               0.0                    0
12   0.0000               0.0                    0
13   0.0000               0.0                    0
14  14.4090               0.0                  165
15   9.8616               0.0                  711
16  41.0000              69.9                 2727
17  44.1000               0.0                 3159
18   0.0000               0.0                    0
19   0.0000               0.0                    0
20   0.0000               0.0                    0
21   0.0000               0.0                    0
22   0.0000               0.0                    0
23   0.0000               0.0                    0
24   0.0000               0.0                    0
25  49.4000              73.3                 5423
26   0.0000               0.0                    0
27   0.0000               0.0                    0
28   0.0000               0.0                    0
29   0.0000               0.0                    0
30   9.8616               0.0                  711
⋮   ⋮                    ⋮                    ⋮
229  0.0000               0.0                    0
230  0.0000               0.0                    0
231  0.0000               0.0                    0
232  0.0000               0.0                    0
233  0.0000               0.0                    0
234  0.0000               0.0                    0
235  0.0000               0.0                    0
236  0.0000               0.0                    0
237  0.0000               0.0                    0
238  0.0000               0.0                    0
239 26.5800              72.3                 2578
240  0.0000               0.0                    0
241  0.0000               0.0                    0
242 10.4981               0.0                 1721
243  0.0000               0.0                    0
244  0.0000               0.0                    0
245  0.0000               0.0                    0
246 12.4130               0.0                   77
247 13.5710               0.0                   64
248  0.0000               0.0                    0
249  0.0000               0.0                    0
250  0.0000               0.0                    0
251  0.0000               0.0                    0
252  0.0000               0.0                    0
253  3.7615               0.0                    0
254 13.8730               0.0                   56
255  0.0000               0.0                    0
256  0.0000               0.0                    0
257  9.8616               0.0                  711
258  0.0000               0.0                    0
    num_TADs_tes_flank TE_pvalues_   N2pair
1   0                   4.662432e-01  1
2   0                   8.937764e-08 NA
3   5                   9.404343e-02 NA
4   0                   9.404343e-02 NA
5   0                   5.012191e-01 NA
6   0                   1.841332e-01 NA
7   0                  -5.629672e-01 NA
8   0                   6.873047e-01 NA
9   0                  -1.902636e-01 NA
10  0                  -2.166980e-03 NA
11  0                   1.099460e-08 NA
12  0                   4.030828e-04 NA
13  0                   5.324425e-01 NA
14  3                   7.913989e-10 NA
15  0                   6.591659e-01 NA
16  0                   5.658081e-11 NA
17  3                   1.050873e-08 NA
18  0                  -6.488169e-01 18
19  0                  -5.735418e-01 19
20  0                   1.268785e-15 NA
21  0                   9.353074e-01 21
22  0                   7.860387e-01 NA
23  0                   8.550896e-04 NA
24  0                  -8.755938e-01 NA
25  0                  -3.949962e-01 25
26  0                   8.088822e-02 26
27  0                  -9.271755e-01 NA
28  0                   3.705097e-02 28
29  0                   6.209151e-01 NA
30  0                   4.899797e-01 NA
⋮   ⋮                  ⋮             ⋮
229 0                   7.739748e-02 NA
230 0                  -9.469662e-01 NA

# Write

In [5]:
fwrite(tmp, 'subset_watershed_input.tsv', sep='\t', na=NA)
fwrite(tmp,   'full_watershed_input.tsv', sep='\t', na=NA)

In [6]:
system('gcloud storage cp "subset_watershed_input.tsv" "$WORKSPACE_BUCKET"')
system('gcloud storage cp   "full_watershed_input.tsv" "$WORKSPACE_BUCKET"')

# Run `predict_watershed.R`

In [7]:
old_wd <- setwd('Watershed_with_tweaks')

system(paste('Rscript predict_watershed.R',
  '--training_input    ../subset_watershed_input.tsv',
  '--prediction_input  ../subset_watershed_input.tsv',
  '--number_dimensions 1',
  '--output_prefix     watershed_output',
  '--model_name        Watershed_exact'
), intern=T)

system('gcloud storage cp watershed_output_* $WORKSPACE_BUCKET/data/derived/')

out <- fread('watershed_output_posterior_probability.txt')

setwd(old_wd)

 [1] "Only RIVER can be run on data with 1 dimension."
 [2] " Changing model to RIVER."
 [3] "########################"
 [4] "ITERATION 1"
 [5] "Average total norm: 0.063294138055469"
 [6] "########################"
 [7] "ITERATION 2"
 [8] "Average total norm: 0.0174892457352731"
 [9] "########################"
[10] "ITERATION 3"
[11] "Average total norm: 0.0143399376904429"
[12] "########################"
[13] "ITERATION 4"
[14] "Average total norm: 0.0130469152098088"
[15] "########################"
[16] "ITERATION 5"
[17] "Average total norm: 0.0121742538981155"
[18] "########################"
[19] "ITERATION 6"
[20] "Average total norm: 0.0135662690914277"
[21] "########################"
[22] "ITERATION 7"
[23] "Average total norm: 0.0226171970930195"
[24] "########################"
[25] "ITERATION 8"
[26] "Average total norm: 0.0137375660226994"
[27] "########################"
[28] "ITERATION 9"
[29] "Average total norm: 0.00733365484763117"
[30] "########################"
[31] "ITERATION 10"
[32] "Average total norm: 0.00542984047557571"
[33] "########################"
[34] "ITERATION 11"
[35] "Average total norm: 0.00436295605561169"
[36] "########################"
[37] "ITERATION 12"
[38] "Average total norm: 0.00351021761505342"
[39] "########################"
[40] "ITERATION 13"
[41] "Average total norm: 0.00282014734019624"
[42] "########################"
[43] "ITERATION 14"
[44] "Average total norm: 0.00225497089685684"
[45] "########################"
[46] "ITERATION 15"
[47] "Average total norm: 0.00181152538747159"
[48] "########################"
[49] "ITERATION 16"
[50] "Average total norm: 0.00147537622076324"
[51] "########################"
[52] "ITERATION 17"
[53] "Average total norm: 0.00116046463312169"
[54] "########################"
[55] "ITERATION 18"
[56] "Average total norm: 0.000920664898049844"
[57] "########################"
[58] "ITERATION 19"
[59] "Average total norm: 0.000756774747048177"
[60] "########################"
[61] "ITERATION 20"
[62] "Average total norm: 0.000616696119189067"
[63] "########################"
[64] "ITERATION 21"
[65] "Average total norm: 0.000499531485230761"
[66] "########################"
[67] "ITERATION 22"
[68] "Average total norm: 0.000406513332475786"
[69] "########################"
[70] "ITERATION 23"
[71] "Average total norm: 0.000332466600118931"
[72] "########################"
[73] "ITERATION 24"
[74] "Average total norm: 0.000280811782938701"
[75] "########################"
[76] "ITERATION 25"
[77] "Average total norm: 0.000206841598304188"
[78] "########################"
[79] "ITERATION 26"
[80] "Average total norm: 0.00016205999207367"
[81] "########################"
[82] "ITERATION 27"
[83] "Average total norm: 0.000148850386202243"
[84] "########################"
[85] "ITERATION 28"
[86] "Average total norm: 0.000130583099591103"
[87] "########################"
[88] "ITERATION 29"
[89] "Average total norm: 0.000100551150881007"
[90] "########################"
[91] "ITERATION 30"
[92] "Average total norm: 9.94429762733631e-05"
[93] "Watershed converged"
[94] "here"

Below are the posterior probabilities output for each gene-individual pair:

In [8]:
out

    sample_names
1   HG00146:ENSG00000174807:UW_VH_3482
2   NA18553:ENSG00000168303:DUP_gs_CNV_7_40131223_40160568
3   HG03127:ENSG00000181192:DUP_gs_CNV_10_12111903_12124450
4   HG03127:ENSG00000181192:DUP_gs_CNV_10_12102547_12113247
5   HG03097:ENSG00000140470:DEL_pindel_43036
6   HG03118:ENSG00000162734:BI_GS_DEL1_B2_P0161_179
7   HG03084:ENSG00000138639:DEL_pindel_12414
8   NA18522:ENSG00000082068:DEL_pindel_15235
9   NA19719:ENSG00000184226:DUP_uwash_chr13_66891604_66901672
10  HG02090:ENSG00000111679:BI_GS_DEL1_B2_P1966_722
11  NA20876:ENSG00000184226:BI_GS_DEL1_B3_P2161_2
12  HG01055:ENSG00000133019:UW_VH_8124
13  HG02583:ENSG00000145781:UW_VH_14273
14  HG02731:ENSG00000171759:UW_VH_4103
15  HG03247:ENSG00000051620:DEL_pindel_20533
16  NA12828:ENSG00000146731:DUP_uwash_chr7_56031072_56186821
17  HG02494:ENSG00000159377:DUP_delly_DUP23941
18  NA19338:ENSG00000107959:BI_GS_DEL1_B3_P1691_7
19  NA18621:ENSG00000172456:DEL_pindel_738
20  HG00663:ENSG00000170745:DUP_gs_CNV_2_17937146_18216823
21  HG01853:ENSG00000174807:UW_VH_13686
22  HG03135:ENSG00000152078:UW_VH_22151
23  HG00141:ENSG00000169926:DUP_uwash_chr15_31110505_31330839
24  HG01363:ENSG00000116667:BI_GS_DEL1_B2_P0185_310
25  HG02481:ENSG00000130764:DUP_gs_CNV_1_3734485_3844788
26  HG02545:ENSG00000165752:UW_VH_8079
27  HG04177:ENSG00000184226:UW_VH_16198
28  HG01125:ENSG00000116667:DEL_pindel_1695
29  NA19385:ENSG00000198876:BI_GS_DEL1_B5_P1580_84
30  NA18504:ENSG00000051620:DEL_pindel_20533
⋮   ⋮
229 HG02471:ENSG00000168282:DEL_pindel_40224
230 NA19393:ENSG00000172403:UW_VH_8741
231 HG03091:ENSG00000184226:DUP_uwash_chr13_66891604_66901672
232 NA19404:ENSG00000082068:BI_GS_DEL1_B5_P0923_417
233 HG02429:ENSG00000138639:DEL_pindel_12421
234 HG01809:ENSG00000082068:DEL_pindel_15237
235 HG01669:ENSG00000172456:DEL_pindel_734
236 HG02026:ENSG00000184226:UW_VH_6503
237 HG01812:ENSG00000071189:DEL_pindel_21870
238 HG02580:ENSG00000165752:UW_VH_8079
239 HG03064:ENSG00000181192:DUP_uwash_chr10_12092804_12171370
240 HG03311:ENSG00000162734:BI_GS_DEL1_B2_P0161_179
241 HG00463:ENSG00000182308:BI_GS_DEL1_B3_P0735_35
242 HG03696:ENSG00000178038:DUP_gs_CNV_3_46667900_46756660
243 HG02888:ENSG00000172403:UW_VH_8741
244 HG00533:ENSG00000107959:DUP_gs_CNV_10_3179999_3227801
245 NA18749:ENSG00000172456:DEL_pindel_738
246 NA19338:ENSG00000035115:BI_GS_DEL1_B4_P0251_46
247 HG01912:ENSG00000174807:UW_VH_3482
248 HG01853:ENSG00000166387:DUP_gs_CNV_11_7545083_7650780
249 HG01988:ENSG00000184226:DUP_uwash_chr13_66891604_66901672
250 HG01965:ENSG00000116667:BI_GS_DEL1_B2_P0185_348
251 HG03166:ENSG00000063438:DUP_delly_DUP66791
252 HG01606:ENSG00000100505:BI_GS_DEL1_B5_P2261_114
253 HG02494:ENSG00000171759:BI_GS_DEL1_B2_P2062_577
254 HG02624:ENSG00000184022:DUP_gs_CNV_1_248572358_248596103
255 HG01363:ENSG00000168280:BI_GS_DEL1_B1_P0400_8
256 NA12889:ENSG00000175868:DUP_gs_CNV_11_14873676_14919955
257 HG02981:ENSG00000051620:DEL_pindel_20533
258 HG02545:ENSG00000152078:UW_VH_22151
    Watershed_posterior_outlier_signal_1 GAM_posterior_outlier_signal_1
1   3.335645e-03                         0.1518288
2   9.769242e-01                         0.8751248
3   9.907413e-01                         0.9190249
4   9.902834e-01                         0.9659229
5   4.878662e-03                         0.1910408
6   3.171402e-02                         0.3780300
7   8.526750e-03                         0.1194460
8   5.245475e-03                         0.0850104
9   3.506919e-02                         0.2269041
10  3.666136e-05                         0.5140968
11  2.115462e-01                         0.2391410
12  1.953484e-01                         0.2157343
13  3.048750e-02                         0.1860972
14  6.435076e-01                         0.3944157
15  2.744086e-03                         0.1100802
16  9.927376e-01                         0.9071777
17  9.942850e-01                         0.6284512
18  2.240998e-02                         0.1526917
19  8.626332e-03                         0.1276207
20  9.579561e-01                         0.8012981
21  1.537840e-02                         0.1301829
22  8.234592e-03                         0.1342535
23  9.870078e-01                         0.9994381
24  1.764542e-02                         0.1597357
25  9.936337e-01                         0.7825348
26  6.568970e-01                         0.5366568
27  3.927674e-02                         0.3580659
28  5.112519e-01                         0.2447842
29  2.588782e-02                         0.2520272
30  2.744086e-03                         0.1100802
⋮   ⋮                                    ⋮
229 0.383048136                          0.33041750
230 0.006499893                          0.06004048
231 0.035069193                          0.22690407
232 0.001987197                          0.12645290
233 0.004832072                          0.15109096
234 0.006600950                          0.18372438
235 0.005018865                          0.22023391
236 0.023378627                          0.16145721
237 0.012075228                          0.26426054
238 0.070609623                          0.53665679
239 0.997546792                          0.96735269
240 0.031714016                          0.37802997
241 0.983642637                          0.97211558
242 0.999668283                          0.97195673
243 0.006499893                          0.06004048
244 0.966850086                          0.80301872
245 0.008626332                          0.12762072
246 0.031491490                          0.17737112
247 0.003335645                          0.15182882
248 0.323829700                          0.79497423
249 0.035069193                          0.22690407
250 0.023053592                          0.10968096
251 0.993545533                          0.92145627
252 0.009074563                          0.14445570
253 0.002383153                          0.09533753
254 0.969913634                          0.73652480
255 0.849270015                          0.48522387
256 0.993716162                          0.96411196
257 0.002744086                          0.11008015
258 0.008234592                          0.13425354